#!/bin/sh
#
#   Resource Agent for managing hetzner cloud floating ip resources.
#
#   License:      MIT License (MIT)
#   Thank Sven Speckmaier for the inspiration

#######################################################################
# Initialization:

: ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat}
. ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs

: OCF_RESKEY_ip=
: OCF_RESKEY_api_token=
FLOATING_IP=${OCF_RESKEY_ip}
API_TOKEN=${OCF_RESKEY_api_token}

#######################################################################

#######################################################################
# Helper:

ip_init() {
	SERVER_ID="$(server_id)"
	FLOATING_IP_ID="$(ip_to_id)"
}

server_id() {
	curl -f -s -H "Authorization: Bearer $API_TOKEN" \
		"https://api.hetzner.cloud/v1/servers?name=$(hostname)" | jq 'if (.servers | length) > 0 then .servers[0].id else error("Error: No servers found") end'
}

ip_to_id() {
	curl -f -s -H "Authorization: Bearer $API_TOKEN" \
		https://api.hetzner.cloud/v1/floating_ips | jq --arg FLOATING_IP "$FLOATING_IP" \
			'if any(.floating_ips[]; select(.ip == $FLOATING_IP)) then .floating_ips[0].id else error("No Float IP found") end'
}

ip_served() {
	curl -f -s -H "Authorization: Bearer $API_TOKEN" "https://api.hetzner.cloud/v1/floating_ips" | \
	jq --arg FLOATING_IP "$FLOATING_IP" --arg SERVER_ID "$SERVER_ID" '
	  if any(.floating_ips[]; select(.ip == $FLOATING_IP)) then
	    if any(.floating_ips[]; select(.server == ($SERVER_ID|tonumber) and .ip == $FLOATING_IP)) then
	      "ok"
	    else
	      "no"
	    end
	  else
	    "not found"
	  end
	' -r
}

ip_validate() {
	check_binary curl

	check_binary jq

	if [ -z "$SERVER_ID" ] ; then
		echo "hostname $(hostname) not found in cloud api"
		exit $OCF_ERR_CONFIGURED
	fi

	if [ -z "$FLOATING_IP_ID" ] ; then
		echo "floating_ip $FLOATING_IP not found in cloud api"
		exit $OCF_ERR_CONFIGURED
	fi
}

#######################################################################

#######################################################################
# Actions:
ip_usage() {
	cat <<END
usage: $0 {start|stop|status|monitor|validate-all|meta-data}

Expects to have a fully populated OCF RA-compliant environment set.
END
}

ip_start() {
	while ! ( curl -f -s -X POST \
	  	-H "Content-Type: application/json" \
	  	-H "Authorization: Bearer $API_TOKEN"  \
		  -d '{"server":'$SERVER_ID'}' \
		    "https://api.hetzner.cloud/v1/floating_ips/${FLOATING_IP_ID}/actions/assign" \
			 > /dev/null ) ; do
		sleep 1s
	done

	exit $OCF_SUCCESS
}

ip_stop() {
	if ! ip_served ; then
		exit $OCF_SUCCESS
	fi

	while ! ocf_run -q curl -f -s -X POST -H "Content-Type: application/json" -H \
		"Authorization: Bearer $API_TOKEN" \
		"https://api.hetzner.cloud/v1/floating_ips/${FLOATING_IP_ID}/actions/unassign"
	do sleep 1s
	done

	exit $OCF_SUCCESS
}

ip_monitor() {
	local ip_status="$(ip_served)"

	case "${ip_status}" in
	"ok")
		exit $OCF_SUCCESS
		;;
	"no")
		exit $OCF_NOT_RUNNING
		;;
	"not found"|*)
		exit $OCF_ERR_GENERIC
		;;
	esac
}

meta_data() {
	cat <<END
<?xml version="1.0"?>
<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
<resource-agent name="FloatingIP" version="0.1">
  <version>0.1</version>
  <longdesc lang="en">
Manage a hetzner cloud floating ip as cloud ressource.
Only routing the ip to this server is taken care of. Pair up with a IPaddr2
resource to properly activate the floating ip.
WARNING: This resource assumes that the hostname on the machine is the same as
its name in the Cloud Api
  </longdesc>
  <shortdesc lang="en">Manage a hetzner cloud floating ip as cloud ressource.</shortdesc>
  <parameters>
    <parameter name="ip" unique="1" required="1">
      <longdesc lang="en">
		The ip address to route to this host
		e.g. 66.77.88.99
      </longdesc>
      <shortdesc lang="en">ip address</shortdesc>
      <content type="string"/>
    </parameter>
    <parameter name="api_token" unique="0" required="1">
      <longdesc lang="en">
		The api token to access the hetzner cloud api. Created in Access/Api-Tokens under 
https://console.hetzner.cloud</longdesc>
      <shortdesc lang="en">Token for hetzner cloud api</shortdesc>
      <content type="string" default="false"/>
    </parameter>
  </parameters>
  <actions>
    <action name="start"        timeout="20" />
    <action name="stop"         timeout="20" />
    <action name="monitor"      timeout="20"
                                interval="10" depth="0" />
    <action name="reload"       timeout="20" />
    <action name="migrate_to"   timeout="20" />
    <action name="migrate_from" timeout="20" />
    <action name="meta-data"    timeout="5" />
    <action name="validate-all"   timeout="20" />
  </actions>
</resource-agent>
END
}

#######################################################################

#######################################################################
# Entrypoint:

case $__OCF_ACTION in
meta-data)	meta_data
		exit $OCF_SUCCESS
		;;
usage|help)	ip_usage
		exit $OCF_SUCCESS
		;;
esac

ip_init
ip_validate

case $__OCF_ACTION in
start)		ip_start
		;;
stop)		ip_stop
		;;
status)		ip_status=`ip_served`
		if [ $ip_status = "ok" ]; then
			echo "running"
			exit $OCF_SUCCESS
		else
			echo "stopped"
			exit $OCF_NOT_RUNNING
		fi
		;;
monitor) ip_monitor
		;;
validate-all)	;;
*)		ip_usage
		exit $OCF_ERR_UNIMPLEMENTED
		;;
esac
#######################################################################
